server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

  rabbitmq:
    host: rabbitmq
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true


