global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'test-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['test-service-app:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: [ 'rabbitmq-exporter:9419' ]